name: Publish helm chart to artifacthub

on:
  release:
    types: 
      - published

env:
  package_version: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check dir
        run: pwd && ls -ltr

      - name: Change chart version
        run: |
          sed -i 's/1.0.0-alpha.69/${package_version}/g' helm/Chart.yml 

      - name: Check the version
        run: cat helm/Chart.yml

      # - name: Set up Helm
      #   uses: azure/setup-helm@v4.3.0

      # - name: Package Helm Chart
      #   run: |
      #     helm package ./charts/mychart  # 根据实际 Helm chart 路径来调整

      # # 5. Checkout 仓库 2（存放打包后的 Helm 包）
      # - name: Checkout repository 2
      #   uses: actions/checkout@v2
      #   with:
      #     repository: your-username/repo-2  # 替换为存放 Helm 包的仓库
      #     token: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub Token 授权

      # # 6. 移动打包后的 Helm 包到仓库 2
      # - name: Move Helm Chart package to repo 2
      #   run: |
      #     mv ./charts/mychart-*.tgz ./  # 假设文件名是 mychart-版本号.tgz

      # # 7. 提交并推送到仓库 2
      # - name: Commit and push Helm package to repo 2
      #   run: |
      #     git config --global user.name "GitHub Actions"
      #     git config --global user.email "actions@github.com"
      #     git add .
      #     git commit -m "Update Helm package"
      #     git push origin main  # 推送到仓库 2 的 main 分支
